### ISSUE TITLE
origins of data

### ISSUE THREAD

**Issue by benjaminapetersen** [BTMorton/dnd-5e-srd#13]
Curious to know the origins of the data, for legal reasons, how to verify its only SRD.  Thx!

**Comment by BTMorton** [comment]
I took the PDF of the 5e SRD (a while ago, it may have changed since) and ran it through a PDF to markdown converter. Then I manually went through the converted markdown file to standardise things like headings and make sure it all converted correctly. I then split that into the various chapters (see the [markdown folder](https://github.com/BTMorton/dnd-5e-srd/tree/master/markdown)) for ease of maintenance.

Then I used [marked](https://www.npmjs.com/package/marked) and a [custom renderer](https://github.com/BTMorton/dnd-5e-srd/blob/master/renderer.ts) to convert the markdown to [JSON](https://github.com/BTMorton/dnd-5e-srd/tree/master/json) and [YAML](https://github.com/BTMorton/dnd-5e-srd/tree/master/yaml) and then combine the markdown files into [one big file](https://github.com/BTMorton/dnd-5e-srd/blob/master/5esrd.md) which is also converted to [JSON](https://github.com/BTMorton/dnd-5e-srd/blob/master/5esrd.json) and [YAML](https://github.com/BTMorton/dnd-5e-srd/blob/master/5esrd.yaml).

If you're concerned, I can try to find the original PDF I used so you can do your own PDF -> markdown conversion. The markdown -> JSON/YAML conversion code is all in [index.ts](https://github.com/BTMorton/dnd-5e-srd/blob/master/index.ts). It took me at least a week of reading through and fixing markdown to get it into a state where I was happy with the output, though 😛.

**Comment by benjaminapetersen** [comment]
Ha, I believe you!
I've been looking at several repos on github with SRD data in various formats, just trying to figure out which ones have stayed "clean" and which have maybe drifted (for legal reasons).  

Thanks for the info, I have no doubt it was a ton of work.

**Comment by BTMorton** [comment]
Yeah, I've tried to keep it clean as a valid SRD source I know I can use in a friendlier format. It hasn't changed much since the initial conversion, aside from some formatting fixes reported in other issues. I should probably at some point look to see if a newer version has been released that I can update to, but that's such a daunting prospect I probably won't ever get to it!

There are probably plenty of other expanded data sources I'm sure I could use if the need arose, no need to pollute this one.
